name: qt6

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dragontao/qt6
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: qt6.dockerfile
